name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Build with make
      run: make

    - name: Make executable (optional)
      run: chmod +x ./foodDel

    - name: Run the executable
      run: ./foodDel

      
